# Generated by Django 4.2.4 on 2023-09-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_txt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
