# Generated by Django 4.2.4 on 2023-09-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_txt', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
