# Generated by Django 4.2.4 on 2023-09-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_txt', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
